PANDAS BASICS 1

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.__version__

'1.3.4'

In [4]:
np.__version__

'1.20.3'

In [5]:
d=[1,2,6,10,10]

In [6]:
series=pd.Series(data=d)

In [7]:
series

0     1
1     2
2     6
3    10
4    10
dtype: int64

In [8]:
type(series)

pandas.core.series.Series

In [9]:
data=[[1,2,3],[2,5,5]]

In [10]:
data

[[1, 2, 3], [2, 5, 5]]

In [11]:
type(data)

list

In [12]:
ser2=pd.Series(data=data)

In [13]:
ser2 #lines are indexed

0    [1, 2, 3]
1    [2, 5, 5]
dtype: object

In [14]:
data=[1,3,5,8]


In [15]:
data

[1, 3, 5, 8]

In [16]:
df=pd.DataFrame(data=data)

In [17]:
df

0
0  1
1  3
2  5
3  8

In [18]:
type(df) #column+lines are indexed

pandas.core.frame.DataFrame

In [19]:
x=[[1,2,3],[2,5,5]]

In [20]:
df2=pd.DataFrame(x)

In [21]:
df2

0  1  2
0  1  2  3
1  2  5  5

In [22]:
type(df2[0]) #dataframes consist of series

pandas.core.series.Series

In [23]:
string="liste"

In [24]:
mySeries=pd.Series([i for i in string])

In [25]:
mySeries

0    l
1    i
2    s
3    t
4    e
dtype: object

In [26]:
myArr=np.arange(24).reshape(3,8)


In [27]:
myArr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [28]:
myDf=pd.DataFrame(myArr)

In [29]:
myDf

0   1   2   3   4   5   6   7
0   0   1   2   3   4   5   6   7
1   8   9  10  11  12  13  14  15
2  16  17  18  19  20  21  22  23

In [30]:
#myArr=np.arange(24).reshape(3,2,4)
#myDf=pd.DataFrame(myArr) 
        #yaparsak error veriyor boyut sıkıntısı oluyor,multiindex kullanılıyormuş bunlarda.
        #dataframe 2 boyutlu,biz 3 boyutlu array girmeye çalıştık o yüzden hata veriyor.
                                

In [31]:
s=pd.Series() #burda içi boş seri yaptık

C:\Users\OSMANV~1\AppData\Local\Temp/ipykernel_8852/974438083.py:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series() #burda içi boş seri yaptık


In [32]:
type(s) #yaptığımızı seri olarak mı algılıyor,typeına bakıp görelim, evet öyle algılıyor

pandas.core.series.Series

In [33]:
ser=pd.Series([1,5,6,10],name="sayılar")

In [34]:
ser.ndim

1

In [35]:
ser.dtype

dtype('int64')

In [36]:
ser.is_unique #elemanlarının tekrarı yok.Arraylarde çalışmıyor,serilerde çalışıyor.

True

In [37]:
ser

0     1
1     5
2     6
3    10
Name: sayılar, dtype: int64

In [38]:
ser.shape #4 üye,tekboyut

(4,)

In [39]:
ser.values

array([ 1,  5,  6, 10], dtype=int64)

In [40]:
for i in ser.values:
    print(i*2)

2
10
12
20


In [41]:
ser=pd.Series([1,5,6,10,'Ali']) 
#ali girince dtype integer bozuldu. Dtype object diyor şimdi. Bir seride karışık tipte data
#olunca kafası karışıyor,o yüzden içeriği kontrol edip tek tipe değiştirmek lazım.Yoksa seride
#işlem yapmaya başlayınca error veriyor.

In [42]:
ser.dtype #dtype O yani object)

dtype('O')

In [43]:
ser#seriyi çağırınca en altta da dtype belirtilmiş,oradan da kontrol edilebilir

0      1
1      5
2      6
3     10
4    Ali
dtype: object

In [44]:
ser.shape

(5,)

In [45]:
ser.name

In [46]:
for i in ser.values:   #string nedeniyle matematik işlem yapılamaz şimdi buna.     
    print(type(i))     #tüm bu komutlar da veriyi evirip çevirip ne durumda 
                       #olduğunu anlamana yarıyor.

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>


In [47]:
myArr=np.arange(100)

In [48]:
nser=pd.Series(myArr)

In [49]:
nser

0      0
1      1
2      2
3      3
4      4
      ..
95    95
96    96
97    97
98    98
99    99
Length: 100, dtype: int32

In [50]:
nser.tail(7)

93    93
94    94
95    95
96    96
97    97
98    98
99    99
dtype: int32

In [51]:
nser.head(4)

0    0
1    1
2    2
3    3
dtype: int32

In [52]:
data=np.array(["a","b","c","d"])

In [53]:
seri2=pd.Series(data)

In [54]:
seri2

0    a
1    b
2    c
3    d
dtype: object

In [55]:
seri3=pd.Series(data,index=[100,200,600,400])

In [56]:
seri3

100    a
200    b
600    c
400    d
dtype: object

In [57]:
data={"a":1,"b":3,"c":10,"d":11}

In [58]:
Seri4=pd.Series(data)


In [59]:
Seri4

a     1
b     3
c    10
d    11
dtype: int64

In [60]:
Seri5=pd.Series(data,index=["b","c","d","e","b"])

In [61]:
Seri5


b     3.0
c    10.0
d    11.0
e     NaN
b     3.0
dtype: float64

In [62]:
Seri6=pd.Series(10,index=[1,2,3,4,5])

In [63]:
Seri6

1    10
2    10
3    10
4    10
5    10
dtype: int64

In [64]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])

In [65]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [66]:
s[0]

1

In [67]:
s[:3]

a    1
b    2
c    3
dtype: int64

In [68]:
s[-3:]

c    3
d    4
e    5
dtype: int64

In [69]:
s[::2]

a    1
c    3
e    5
dtype: int64

In [70]:
# label indexleme biraz farklı. Sonuçlara dikkat et!!!

In [71]:
s["a"]

1

In [72]:
s["a":"c"] #hem a'yı hem de c'yi dahil etti

a    1
b    2
c    3
dtype: int64

In [73]:
ser1 = pd.Series([1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])


In [74]:
ser2 = pd.Series([1,2,5,4], index = ["USA", "Germany", "Italy", "Japan"])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [75]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [76]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [77]:
ser3=ser1 + ser2

In [78]:
ser3 #kesişim kümesini topladı ama tek serde olanları nan olarak verdi

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [79]:
ser3['Germany':"Japan"]

Germany    4.0
Italy      NaN
Japan      8.0
dtype: float64

In [80]:
ser3.index

Index(['Germany', 'Italy', 'Japan', 'USA', 'USSR'], dtype='object')

In [81]:
ser3.items

<bound method Series.items of Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64>

In [82]:
for index, value in ser3.items():
      print(index,'----',value)

Germany ---- 4.0
Italy ---- nan
Japan ---- 8.0
USA ---- 2.0
USSR ---- nan


In [83]:
'Germany' in ser3 #case sensitive,tırnak içinde.

True

In [84]:
4.0 in ser3 #rakam yazarken tırnak,köşeli parantez falan kullanılmıyor. Yazım doğru.
            #peki neden bulamadı.Çünkü indexleri tarıyor.4.0 var,ama index değer değil.

False

In [85]:
ser3.values

array([ 4., nan,  8.,  2., nan])

In [86]:
4.0 in ser3.values #ilgili columnda aratacaksın

True

In [87]:
ser3["Italy"]=5 ###Italynin değerini 5 yaptık

In [88]:
ser3

Germany    4.0
Italy      5.0
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [89]:
ser3>3

Germany     True
Italy       True
Japan       True
USA        False
USSR       False
dtype: bool

In [90]:
ser3[ser3>3]

Germany    4.0
Italy      5.0
Japan      8.0
dtype: float64

In [91]:
ser3.hasnans

True

In [92]:
ser3.isin([4])

Germany     True
Italy      False
Japan      False
USA        False
USSR       False
dtype: bool

In [93]:
ser3[ser3.isin([4])]

Germany    4.0
dtype: float64

In [94]:
ser3[ser3.isin([4])].values

array([4.])

In [95]:
s = pd.Series(['lama', 'cow', 'lama', 'beetle', 'lama','hippo'], name='animal')

In [96]:
s

0      lama
1       cow
2      lama
3    beetle
4      lama
5     hippo
Name: animal, dtype: object

In [97]:
s[s.isin(["lama","cow"])]

0    lama
1     cow
2    lama
4    lama
Name: animal, dtype: object

In [98]:
s.pop(0)

'lama'

In [99]:
s

1       cow
2      lama
3    beetle
4      lama
5     hippo
Name: animal, dtype: object

In [100]:
a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])

In [101]:
b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])

In [102]:
a

a    1.0
b    1.0
c    1.0
d    NaN
dtype: float64

In [103]:
b

a    1.0
b    NaN
d    1.0
e    NaN
dtype: float64

In [104]:
a+b #bir sayıyı nan ile toplarsan sonuç nan gelir

a    2.0
b    NaN
c    NaN
d    NaN
e    NaN
dtype: float64

In [105]:
a.add(b)

a    2.0
b    NaN
c    NaN
d    NaN
e    NaN
dtype: float64

In [106]:
a.add(b, fill_value=0) #a+bde fill value yapılmıyor,adde kullanmak lazım

a    2.0
b    1.0
c    1.0
d    1.0
e    NaN
dtype: float64

In [107]:
s = pd.Series([20, 21, 12],
              index=['London', 'New York', 'Helsinki'])


In [108]:
s

London      20
New York    21
Helsinki    12
dtype: int64

In [109]:
def binkatı(x):
    return x*1000

In [110]:
s.apply(binkatı) #yazdığımız fonksiyonu seri üzerinde kullanmamızı sağlıyor

London      20000
New York    21000
Helsinki    12000
dtype: int64

In [111]:
s.apply(np.sin)#yani hem senin yazdığın,hem de kütüphanedeki fonksiyonları apply edebilirsin

London      0.912945
New York    0.836656
Helsinki   -0.536573
dtype: float64

In [112]:
tarihler=pd.date_range("2011-01-01", periods = 5, freq="D", tz="US/Eastern" )

In [113]:
tarihler

DatetimeIndex(['2011-01-01 00:00:00-05:00', '2011-01-02 00:00:00-05:00',
               '2011-01-03 00:00:00-05:00', '2011-01-04 00:00:00-05:00',
               '2011-01-05 00:00:00-05:00'],
              dtype='datetime64[ns, US/Eastern]', freq='D')

In [114]:
saatler=pd.date_range("2011-01-01", periods = 5, freq="H", tz="US/Eastern" )

In [115]:
saatler

DatetimeIndex(['2011-01-01 00:00:00-05:00', '2011-01-01 01:00:00-05:00',
               '2011-01-01 02:00:00-05:00', '2011-01-01 03:00:00-05:00',
               '2011-01-01 04:00:00-05:00'],
              dtype='datetime64[ns, US/Eastern]', freq='H')

In [116]:
dateSeri=pd.Series(saatler)

In [117]:
dateSeri

0   2011-01-01 00:00:00-05:00
1   2011-01-01 01:00:00-05:00
2   2011-01-01 02:00:00-05:00
3   2011-01-01 03:00:00-05:00
4   2011-01-01 04:00:00-05:00
dtype: datetime64[ns, US/Eastern]

In [118]:
ser=pd.Series([10,12,13,13],index=["ali","fatma","ömer","melih"],name='yaslar')

In [119]:
print(ser.name)

yaslar


In [120]:
ser

ali      10
fatma    12
ömer     13
melih    13
Name: yaslar, dtype: int64

In [121]:
s=pd.Series([1,2,3,4])

In [122]:
s.agg(min)

1

In [123]:
s.agg([min,max])

min    1
max    4
dtype: int64

In [124]:
s.transform([np.sqrt,np.sin])

sqrt       sin
0  1.000000  0.841471
1  1.414214  0.909297
2  1.732051  0.141120
3  2.000000 -0.756802

In [125]:
ser = pd.Series([390., 350., 30., 20.],index=['Falcon', 'Falcon', 'Parrot', 'Parrot'], name="Max Speed")

In [126]:
ser

Falcon    390.0
Falcon    350.0
Parrot     30.0
Parrot     20.0
Name: Max Speed, dtype: float64

In [127]:
ser.groupby(["a","a","b","b"]).mean()

a    370.0
b     25.0
Name: Max Speed, dtype: float64

In [128]:
ser.groupby(level=0).mean()

Falcon    370.0
Parrot     25.0
Name: Max Speed, dtype: float64

In [129]:
arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]
index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
ser = pd.Series([390., 350., 30., 20.], index=index, name="Max Speed")

In [130]:
ser

Animal  Type   
Falcon  Captive    390.0
        Wild       350.0
Parrot  Captive     30.0
        Wild        20.0
Name: Max Speed, dtype: float64

In [131]:
ser.groupby(level=0).mean()

Animal
Falcon    370.0
Parrot     25.0
Name: Max Speed, dtype: float64

In [132]:
ser.groupby(level=1).mean()

Type
Captive    210.0
Wild       185.0
Name: Max Speed, dtype: float64

In [133]:
ser.describe()   ######çokomelli!!!!!

count      4.000000
mean     197.500000
std      199.895806
min       20.000000
25%       27.500000
50%      190.000000
75%      360.000000
max      390.000000
Name: Max Speed, dtype: float64

In [134]:
ser1=pd.Series(np.arange(3),index=["a","b","c"])

In [135]:
ser1

a    0
b    1
c    2
dtype: int32

In [136]:
ser1.drop(labels=["b"])

a    0
c    2
dtype: int32

In [137]:
ser1

a    0
b    1
c    2
dtype: int32

In [138]:
ser1.drop(labels=["b"],inplace=True) #kalıcı olarak kaldırmak için inplace=True

In [139]:
ser1

a    0
c    2
dtype: int32

In [140]:
midx=pd.MultiIndex(levels=[["lama", "cow", "falcon"],["speed", "weight", "length"]],
                   codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
                            [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [141]:
midx

MultiIndex([(  'lama',  'speed'),
            (  'lama', 'weight'),
            (  'lama', 'length'),
            (   'cow',  'speed'),
            (   'cow', 'weight'),
            (   'cow', 'length'),
            ('falcon',  'speed'),
            ('falcon', 'weight'),
            ('falcon', 'length')],
           )

In [142]:
seri=pd.Series([45,200,1.2,52,65,25,52,96,91], index=midx)

In [143]:
seri

lama    speed      45.0
        weight    200.0
        length      1.2
cow     speed      52.0
        weight     65.0
        length     25.0
falcon  speed      52.0
        weight     96.0
        length     91.0
dtype: float64

In [144]:
seri.drop(labels="cow", level=0 )

lama    speed      45.0
        weight    200.0
        length      1.2
falcon  speed      52.0
        weight     96.0
        length     91.0
dtype: float64

In [145]:
seri.drop(labels="weight", level=1)

lama    speed     45.0
        length     1.2
cow     speed     52.0
        length    25.0
falcon  speed     52.0
        length    91.0
dtype: float64

DATA FRAME

In [146]:
data={"a":[1,2,3,4],"b":["a","b","c","d"]}

In [147]:
aa=pd.DataFrame(data)

In [148]:
aa

a  b
0  1  a
1  2  b
2  3  c
3  4  d

In [149]:
aa.dtypes

a     int64
b    object
dtype: object

In [150]:
aa.mean()

C:\Users\OSMANV~1\AppData\Local\Temp/ipykernel_8852/4149838814.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  aa.mean()


a    2.5
dtype: float64

In [151]:
data={"name":["ali","veli","mehmet"],"age":[18,19,21]}

In [152]:
ab=pd.DataFrame(data)

In [153]:
ab.dtypes

name    object
age      int64
dtype: object

In [154]:
ab

name  age
0     ali   18
1    veli   19
2  mehmet   21

In [155]:
ab=pd.DataFrame(data,index=["1.derece","2.derece","3.derece"])

In [156]:
ab

name  age
1.derece     ali   18
2.derece    veli   19
3.derece  mehmet   21

In [157]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d,dtype=np.int8) #int değerini küçülttük
df

col1  col2
0     1     3
1     2     4

In [158]:
df.dtypes

col1    int8
col2    int8
dtype: object

In [159]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
df

a   b     c
0  1   2   NaN
1  5  10  20.0

In [160]:
df=pd.DataFrame(data,index=["first","second"])

In [161]:
df

a   b     c
first   1   2   NaN
second  5  10  20.0

In [162]:
for i in df.columns:
    print (i)

a
b
c


In [163]:
df.values

array([[ 1.,  2., nan],
       [ 5., 10., 20.]])

In [164]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]


In [165]:
df1 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b'])
df2 = pd.DataFrame(data, index=['first', 'second'], columns=['a', 'b1'])
#column a deyince datadaki 1. ve 2. a'yı veriyor. 
#b1 ise nan çünkü data kümesinde b1 yok

In [166]:
df1

a   b
first   1   2
second  5  10

In [167]:
df2

a  b1
first   1 NaN
second  5 NaN

In [168]:
data={'one':pd.Series([1,2,3],index=["a","b","c"]),
      "two":pd.Series([6,9,5],index=["a","b","d"])} #2 seriden 1 dataframe oluşturmak

In [169]:
aa=pd.DataFrame(data)

In [170]:
aa

one  two
a  1.0  6.0
b  2.0  9.0
c  3.0  NaN
d  NaN  5.0

In [171]:
df.axes


[Index(['first', 'second'], dtype='object'),
 Index(['a', 'b', 'c'], dtype='object')]

In [172]:
df.axes[1]

Index(['a', 'b', 'c'], dtype='object')

In [173]:
df.ndim

2

In [174]:
np.random.randn(7,3)

array([[-2.17832319,  0.00898239, -1.8634883 ],
       [-0.32875521, -0.51008638,  0.03377118],
       [-0.11786473,  2.41192639, -0.89944728],
       [ 0.65807234, -0.62606171, -0.41089479],
       [ 0.32255343, -0.15107191,  0.62206408],
       [-0.346871  ,  1.7637466 , -0.46824157],
       [ 1.66136539, -0.9380908 , -0.50393381]])

In [175]:
df=pd.DataFrame(np.random.randn(4,3),columns=["c1","c2","c3"],index=["a","b","c","d"])

In [176]:
df

c1        c2        c3
a -0.380952  2.832245  0.443813
b  0.299516 -0.798422  0.216838
c  0.934564 -0.297806  2.240582
d  0.829507  2.156460  0.976200

In [177]:
df=pd.DataFrame(np.random.randn(2,2),columns=["col1","col2"])

In [178]:
df

col1      col2
0 -0.415606 -0.833669
1 -0.758720 -1.044363

In [179]:
N=20
df=pd.DataFrame(
{
    "A": pd.date_range(start="2020-01-01", periods=N, freq="D"),
    "B":np.linspace(0, stop=N-1, num=N),
    "C": np.random.rand(N),
    "D": np.random.choice(["low", "medium","high"], N).tolist(),
    "E":np.random.normal(100,10, size=(N)).tolist()
}
)

In [180]:
df

A     B         C       D           E
0  2020-01-01   0.0  0.636405    high  100.107985
1  2020-01-02   1.0  0.159876     low   85.992097
2  2020-01-03   2.0  0.837259     low  121.438437
3  2020-01-04   3.0  0.462902    high   87.754128
4  2020-01-05   4.0  0.290509  medium   98.357083
5  2020-01-06   5.0  0.322749  medium   97.030538
6  2020-01-07   6.0  0.261332  medium   89.755257
7  2020-01-08   7.0  0.120980  medium  111.175744
8  2020-01-09   8.0  0.793790    high  111.299824
9  2020-01-10   9.0  0.162460  medium   98.686843
10 2020-01-11  10.0  0.046195  medium   92.574514
11 2020-01-12  11.0  0.394051     low   90.929423
12 2020-01-13  12.0  0.368225     low   84.042220
13 2020-01-14  13.0  0.914502    high  106.559288
14 2020-01-15  14.0  0.959362    high  111.214204
15 2020-01-16  15.0  0.038896    high   92.690547
16 2020-01-17  16.0  0.207828     low  114.557203
17 2020-01-18  17.0  0.224238     low  101.089652
18 2020-01-19  18.0  0.981922     low  119.954417
19 2020-01-20  19.0  0.226748  medium  109.662752

In [181]:
df.shape

(20, 5)

In [182]:
df.dtypes

A    datetime64[ns]
B           float64
C           float64
D            object
E           float64
dtype: object

In [183]:
df.tail(5)

A     B         C       D           E
15 2020-01-16  15.0  0.038896    high   92.690547
16 2020-01-17  16.0  0.207828     low  114.557203
17 2020-01-18  17.0  0.224238     low  101.089652
18 2020-01-19  18.0  0.981922     low  119.954417
19 2020-01-20  19.0  0.226748  medium  109.662752

In [184]:
df.head(5)

A    B         C       D           E
0 2020-01-01  0.0  0.636405    high  100.107985
1 2020-01-02  1.0  0.159876     low   85.992097
2 2020-01-03  2.0  0.837259     low  121.438437
3 2020-01-04  3.0  0.462902    high   87.754128
4 2020-01-05  4.0  0.290509  medium   98.357083

In [185]:
df.rename(columns={"A":"Tarih","B":"Liner"},index={0:"55"})

Tarih  Liner         C       D           E
55 2020-01-01    0.0  0.636405    high  100.107985
1  2020-01-02    1.0  0.159876     low   85.992097
2  2020-01-03    2.0  0.837259     low  121.438437
3  2020-01-04    3.0  0.462902    high   87.754128
4  2020-01-05    4.0  0.290509  medium   98.357083
5  2020-01-06    5.0  0.322749  medium   97.030538
6  2020-01-07    6.0  0.261332  medium   89.755257
7  2020-01-08    7.0  0.120980  medium  111.175744
8  2020-01-09    8.0  0.793790    high  111.299824
9  2020-01-10    9.0  0.162460  medium   98.686843
10 2020-01-11   10.0  0.046195  medium   92.574514
11 2020-01-12   11.0  0.394051     low   90.929423
12 2020-01-13   12.0  0.368225     low   84.042220
13 2020-01-14   13.0  0.914502    high  106.559288
14 2020-01-15   14.0  0.959362    high  111.214204
15 2020-01-16   15.0  0.038896    high   92.690547
16 2020-01-17   16.0  0.207828     low  114.557203
17 2020-01-18   17.0  0.224238     low  101.089652
18 2020-01-19   18.0  0.981922     low  119.954417
19 2020-01-20   19.0  0.226748  medium  109.662752

In [186]:
df['yeni']=df['E']+df["E"]

In [187]:
df

A     B         C       D           E        yeni
0  2020-01-01   0.0  0.636405    high  100.107985  200.215971
1  2020-01-02   1.0  0.159876     low   85.992097  171.984194
2  2020-01-03   2.0  0.837259     low  121.438437  242.876874
3  2020-01-04   3.0  0.462902    high   87.754128  175.508255
4  2020-01-05   4.0  0.290509  medium   98.357083  196.714165
5  2020-01-06   5.0  0.322749  medium   97.030538  194.061076
6  2020-01-07   6.0  0.261332  medium   89.755257  179.510513
7  2020-01-08   7.0  0.120980  medium  111.175744  222.351489
8  2020-01-09   8.0  0.793790    high  111.299824  222.599648
9  2020-01-10   9.0  0.162460  medium   98.686843  197.373685
10 2020-01-11  10.0  0.046195  medium   92.574514  185.149028
11 2020-01-12  11.0  0.394051     low   90.929423  181.858845
12 2020-01-13  12.0  0.368225     low   84.042220  168.084440
13 2020-01-14  13.0  0.914502    high  106.559288  213.118575
14 2020-01-15  14.0  0.959362    high  111.214204  222.428408
15 2020-01-16  15.0  0.038896    high   92.690547  185.381095
16 2020-01-17  16.0  0.207828     low  114.557203  229.114406
17 2020-01-18  17.0  0.224238     low  101.089652  202.179304
18 2020-01-19  18.0  0.981922     low  119.954417  239.908835
19 2020-01-20  19.0  0.226748  medium  109.662752  219.325504

In [188]:
data={"name":pd.Series(["ali", "ayşe", "fatma", "mehmet"]), 
      "boy":pd.Series([1.70,1.55,1.60,1.90]), "kilo":pd.Series([70,55, 60, 80])}

In [189]:
data


{'name': 0       ali
 1      ayşe
 2     fatma
 3    mehmet
 dtype: object,
 'boy': 0    1.70
 1    1.55
 2    1.60
 3    1.90
 dtype: float64,
 'kilo': 0    70
 1    55
 2    60
 3    80
 dtype: int64}

In [190]:
df=pd.DataFrame(data)
df["BKI"]=df["kilo"]/(df["boy"]*df["boy"])

In [191]:
df

name   boy  kilo        BKI
0     ali  1.70    70  24.221453
1    ayşe  1.55    55  22.892820
2   fatma  1.60    60  23.437500
3  mehmet  1.90    80  22.160665

In [192]:
df.name #bunu kullanmak pek önerilmiyor. Köşeli parantez daha iyi. Sütun adında
        #boşluk varsa sorun çıkıyormuş.

0       ali
1      ayşe
2     fatma
3    mehmet
Name: name, dtype: object

In [193]:
df.pop("boy")


0    1.70
1    1.55
2    1.60
3    1.90
Name: boy, dtype: float64

In [194]:
del df["name"]

In [195]:
df

kilo        BKI
0    70  24.221453
1    55  22.892820
2    60  23.437500
3    80  22.160665

In [196]:
df1=pd.DataFrame([[1,2],[3,4]],columns=["a","b"])

In [197]:
df1

a  b
0  1  2
1  3  4

In [198]:
df2=pd.DataFrame([[5,6],[7,8]],columns =["a","b"])

In [199]:
df2


a  b
0  5  6
1  7  8

In [200]:
df3=df2.append(df1)

In [201]:
df3


a  b
0  5  6
1  7  8
0  1  2
1  3  4

In [202]:
df3.T #T transpozenin kısaltması. Satırla sütunu yer değiştiriyor.

0  1  0  1
a  5  7  1  3
b  6  8  2  4

In [203]:
df3.columns

Index(['a', 'b'], dtype='object')

In [204]:
weather_data={
    "day":["1/1/2017","1/2/2017","1/3/2017","1/4/2017","1/5/2017","1/6/2017"],
    "temperature":[32,35,28,24,31,31],
    "windspeed":[6,7,2,7,4,2],
    "event":["Rainy","Sunny","Snowy","Snowy","Rainy","Sunny"]
    }

df=pd.DataFrame(weather_data)

In [205]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6  Rainy
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2  Snowy
3  1/4/2017           24          7  Snowy
4  1/5/2017           31          4  Rainy
5  1/6/2017           31          2  Sunny

In [206]:
df.info() #boş parantezi asla unutma farklı sonuç alırsın!!!!!!!!!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          6 non-null      object
 1   temperature  6 non-null      int64 
 2   windspeed    6 non-null      int64 
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [207]:
df.describe() #boş parantezi asla unutma farklı sonuç alırsın!!!!!!!!!

temperature  windspeed
count     6.000000   6.000000
mean     30.166667   4.666667
std       3.763863   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.000000   5.000000
75%      31.750000   6.750000
max      35.000000   7.000000

In [208]:
df=pd.DataFrame({
    "col1":np.random.choice(["a","b","c"],10**6),
    "col2":np.random.choice(["a","b","c"],10**6),
    "col3":np.random.choice(["a","b","c"],10**6)
    
})

In [209]:
df #bir milyon satırdan oluşan dataframe ürettik

col1 col2 col3
0         b    b    a
1         a    c    a
2         c    a    c
3         b    c    c
4         b    a    b
...     ...  ...  ...
999995    c    b    a
999996    a    c    c
999997    b    c    a
999998    b    b    a
999999    c    c    b

[1000000 rows x 3 columns]

In [210]:
df.shape


(1000000, 3)

In [211]:
df.col1.value_counts()

b    334021
c    333315
a    332664
Name: col1, dtype: int64

In [212]:
df.describe()

col1     col2     col3
count   1000000  1000000  1000000
unique        3        3        3
top           b        b        a
freq     334021   333685   334017

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 3 columns):
 #   Column  Non-Null Count    Dtype 
---  ------  --------------    ----- 
 0   col1    1000000 non-null  object
 1   col2    1000000 non-null  object
 2   col3    1000000 non-null  object
dtypes: object(3)
memory usage: 22.9+ MB


In [214]:
df=pd.DataFrame(np.arange(10).reshape(5,2))
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [215]:
df=pd.DataFrame(np.arange(10).reshape(-1,2))
df

0  1
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [216]:
rule=df%2==0

In [217]:
df.where(rule)

0   1
0  0 NaN
1  2 NaN
2  4 NaN
3  6 NaN
4  8 NaN

In [218]:
df = pd.DataFrame({"Person":
                   ["John", "Myla", "Lewis", "John", "Myla"],
                   "Age": [24., np.nan, 21., 33, 26],
                   "Single": [False, True, True, True, False]})

In [219]:
df

Person   Age  Single
0   John  24.0   False
1   Myla   NaN    True
2  Lewis  21.0    True
3   John  33.0    True
4   Myla  26.0   False

In [220]:
df.count()

Person    5
Age       4
Single    5
dtype: int64

In [221]:
df.value_counts() 

Person  Age   Single
John    24.0  False     1
        33.0  True      1
Lewis   21.0  True      1
Myla    26.0  False     1
dtype: int64

In [222]:
df.Single.value_counts()

True     3
False    2
Name: Single, dtype: int64

In [223]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['one', 'two', 'three'])


In [224]:
df

one  two  three
mouse     1    2      3
rabbit    4    5      6

In [225]:
df.filter(items=["one","three"])

one  three
mouse     1      3
rabbit    4      6

In [226]:
df.filter(["one","three"])

one  three
mouse     1      3
rabbit    4      6

In [227]:
df = pd.DataFrame([('bird', 389.0),
                   ('bird', 24.0),
                   ('mammal', 80.5),
                   ('mammal', np.nan)],
                  index=['falcon', 'parrot', 'lion', 'monkey'],
                  columns=('class', 'max_speed'))

In [228]:
df

class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [229]:
df.reset_index() #boş parantez koymazsan hatalı sonuç alıyorsun

index   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [230]:
df.add_prefix("col_")

col_class  col_max_speed
falcon      bird          389.0
parrot      bird           24.0
lion      mammal           80.5
monkey    mammal            NaN

In [231]:
np.random.seed(101)

In [232]:
String="A B C D E"

In [233]:
Sutun="W X Y Z"

In [234]:
df=pd.DataFrame(np.random.randn(5,4), index=String.split(), columns= Sutun.split())

In [235]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [236]:
type(df["W"])

pandas.core.series.Series

In [237]:
selection=["W","Y"]

In [238]:
df[selection]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [239]:
df["C":]

W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [240]:
df["NEW"]=df["X"]+df["Y"]

In [241]:
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  1.536102
B  0.651118 -0.319318 -0.848077  0.605965 -1.167395
C -2.018168  0.740122  0.528813 -0.589001  1.268936
D  0.188695 -0.758872 -0.933237  0.955057 -1.692109
E  0.190794  1.978757  2.605967  0.683509  4.584725

In [242]:
df.drop(["NEW"],axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [243]:
df.drop(["A","C"],axis=0)

W         X         Y         Z       NEW
B  0.651118 -0.319318 -0.848077  0.605965 -1.167395
D  0.188695 -0.758872 -0.933237  0.955057 -1.692109
E  0.190794  1.978757  2.605967  0.683509  4.584725

In [244]:
df = pd.DataFrame(np.random.randn(8, 4),
index = ['a','b','c','d','e','f','g','h'], columns = ['A', 'B', 'C', 'D'])

In [245]:
df

A         B         C         D
a  0.302665  1.693723 -1.706086 -1.159119
b -0.134841  0.390528  0.166905  0.184502
c  0.807706  0.072960  0.638787  0.329646
d -0.497104 -0.754070 -0.943406  0.484752
e -0.116773  1.901755  0.238127  1.996652
f -0.993263  0.196800 -1.136645  0.000366
g  1.025984 -0.156598 -0.031579  0.649826
h  2.154846 -0.610259 -0.755325 -0.346419

In [246]:
df.loc[:,"C"]

a   -1.706086
b    0.166905
c    0.638787
d   -0.943406
e    0.238127
f   -1.136645
g   -0.031579
h   -0.755325
Name: C, dtype: float64

In [247]:
df.loc[:,["A","C"]]

A         C
a  0.302665 -1.706086
b -0.134841  0.166905
c  0.807706  0.638787
d -0.497104 -0.943406
e -0.116773  0.238127
f -0.993263 -1.136645
g  1.025984 -0.031579
h  2.154846 -0.755325

In [248]:
df.loc[["a","d","g"],["C","D"]]

C         D
a -1.706086 -1.159119
d -0.943406  0.484752
g -0.031579  0.649826

In [249]:
df.loc["a":"c","A":"D"] 

A         B         C         D
a  0.302665  1.693723 -1.706086 -1.159119
b -0.134841  0.390528  0.166905  0.184502
c  0.807706  0.072960  0.638787  0.329646

In [250]:
df.loc["d"]>0

A    False
B    False
C    False
D     True
Name: d, dtype: bool

In [251]:
rekt=df.loc["c":"d","B":"C"]>0

In [252]:
df.loc["c":"d","B":"C"][rekt]

B         C
c  0.07296  0.638787
d      NaN       NaN

In [253]:
#c ve d satırları ile B ve C sütunlarınn -0.7 ile -0.6 arasında olan sayılarını getirmek

df.loc["c":"d",["B","C"]][(df.loc["c":"d",["B","C"]]>-0.7)&(df.loc["c":"d",["B","C"]]<-0.6)]

B   C
c NaN NaN
d NaN NaN

In [254]:
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])

In [255]:
df

A         B         C         D
0  0.147027 -0.479448  0.558769  1.024810
1 -0.925874  1.862864 -1.133817  0.610478
2  0.386030  2.084019 -0.376519  0.230336
3  0.681209  1.035125 -0.031160  1.939932
4 -1.005187 -0.741790  0.187125 -0.732845
5 -1.382920  1.482495  0.961458 -2.141212
6  0.992573  1.192241 -1.046780  1.292765
7 -1.467514 -0.494095 -0.162535  0.485809

In [256]:
df.iloc[:4]

A         B         C         D
0  0.147027 -0.479448  0.558769  1.024810
1 -0.925874  1.862864 -1.133817  0.610478
2  0.386030  2.084019 -0.376519  0.230336
3  0.681209  1.035125 -0.031160  1.939932

In [257]:
df.loc[:4]

A         B         C         D
0  0.147027 -0.479448  0.558769  1.024810
1 -0.925874  1.862864 -1.133817  0.610478
2  0.386030  2.084019 -0.376519  0.230336
3  0.681209  1.035125 -0.031160  1.939932
4 -1.005187 -0.741790  0.187125 -0.732845

In [258]:
df.iloc[1:3,2:]

C         D
1 -1.133817  0.610478
2 -0.376519  0.230336

In [259]:
df.iloc[3:5,2:]

C         D
3 -0.031160  1.939932
4  0.187125 -0.732845

In [260]:
df.iloc[6:,2:]

C         D
6 -1.046780  1.292765
7 -0.162535  0.485809

In [261]:
df.iloc[[0,3,5],[1,3]]

B         D
0 -0.479448  1.024810
3  1.035125  1.939932
5  1.482495 -2.141212

In [262]:
rekt=df.iloc[[2,4],[1,3]]>0

In [263]:
df.iloc[[2,4],[1,3]][rekt]

B         D
2  2.084019  0.230336
4       NaN       NaN

In [264]:
df[df>0]

A         B         C         D
0  0.147027       NaN  0.558769  1.024810
1       NaN  1.862864       NaN  0.610478
2  0.386030  2.084019       NaN  0.230336
3  0.681209  1.035125       NaN  1.939932
4       NaN       NaN  0.187125       NaN
5       NaN  1.482495  0.961458       NaN
6  0.992573  1.192241       NaN  1.292765
7       NaN       NaN       NaN  0.485809

In [265]:
df.iloc[:,1]>0

0    False
1     True
2     True
3     True
4    False
5     True
6     True
7    False
Name: B, dtype: bool

In [266]:
df.iloc[:,2][df.iloc[:,1]>0]

1   -1.133817
2   -0.376519
3   -0.031160
5    0.961458
6   -1.046780
Name: C, dtype: float64

In [267]:
df.B>0

0    False
1     True
2     True
3     True
4    False
5     True
6     True
7    False
Name: B, dtype: bool

In [268]:
df[df.B>0]

A         B         C         D
1 -0.925874  1.862864 -1.133817  0.610478
2  0.386030  2.084019 -0.376519  0.230336
3  0.681209  1.035125 -0.031160  1.939932
5 -1.382920  1.482495  0.961458 -2.141212
6  0.992573  1.192241 -1.046780  1.292765

In [269]:
df[df.B>0].C

1   -1.133817
2   -0.376519
3   -0.031160
5    0.961458
6   -1.046780
Name: C, dtype: float64

In [270]:
df=pd.DataFrame(np.arange(12).reshape(4,3),columns=["col1","col2","col3"])

In [271]:
df

col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8
3     9    10    11

In [272]:
df.col1.values

array([0, 3, 6, 9])

In [273]:
df.col1.values[3]

9

In [274]:
for i in range(len(df.col1.values)):
    df.col1.values[i]+=10

In [275]:
df.col1


0    10
1    13
2    16
3    19
Name: col1, dtype: int32